-- 完整客户数据导入（包含正确的298 - SHYQH）

-- 先备份
-- copy data.db data_backup_before_import.db

-- 插入所有客户（去重版）
INSERT OR IGNORE INTO customers (customer_name, tax_no, company_name, created_at) VALUES 
-- 260-279 段
('262 - SHYQ', '', '', datetime('now')),
('263 - SHDYB', '', '', datetime('now')),
('264 - SHFY', '', '', datetime('now')),
('265 - SHJDY', '', '', datetime('now')),
('266 - SHYH', '', '', datetime('now')),
('267 - SHJCR', '', '', datetime('now')),
('268 - SHSC', '', '', datetime('now')),
('269 - SHFCH', '', '', datetime('now')),
('270 - SHFX', '', '', datetime('now')),
('271 - SHLC', '', '', datetime('now')),
('272 - SHEZZ', '', '', datetime('now')),
('273 - SHJM', '', '', datetime('now')),
('274 - SHKK', '', '', datetime('now')),
('275 - SHCSI', '', '', datetime('now')),
('276 - SHJYD', '', '', datetime('now')),
('277 - HNXTCFC', '', '', datetime('now')),
('279 - SHYP', '', '', datetime('now')),

-- 280-299 段
('280 - 用户名用户3', '', '', datetime('now')),
('281 - SHYYH', '', '', datetime('now')),
('282 - BSYX-KY', '', '', datetime('now')),
('283 - mayan', '', '', datetime('now')),
('284 - mayan2', '', '', datetime('now')),
('285 - NW', '', '', datetime('now')),
('286 - SHXL', '', '', datetime('now')),
('288 - HZJCGJ', '', '', datetime('now')),
('289 - SHJH', '', '', datetime('now')),
('290 - SHLX', '', '', datetime('now')),
('291 - SHHQJ', '', '', datetime('now')),
('292 - NBYBH', '', '', datetime('now')),
('293 - HQ', '', '', datetime('now')),
('294 - BSYX-HY', '', '', datetime('now')),
('295 - SHWX', '', '', datetime('now')),
('296 - SHCC', '', '', datetime('now')),
('297 - SHZX', '', '', datetime('now')),
('298 - SHYQH', '', '', datetime('now')),  -- ✅ 正确的298
('299 - SHYT', '', '', datetime('now')),

-- 300-319 段
('300 - ZUJD', '', '', datetime('now')),
('301 - GD', '', '', datetime('now')),
('302 - SKB', '', '', datetime('now')),
('303 - CLARK', '', '', datetime('now')),
('304 - ZJJM', '', '', datetime('now')),
('305 - SFGJ', '', '', datetime('now')),
('306 - JHHGM', '', '', datetime('now')),
('307 - DLHGY', '', '', datetime('now')),
('308 - MKKE', '', '', datetime('now')),
('309 - MYF', '', '', datetime('now')),
('310 - BSYX-LM', '', '', datetime('now')),
('311 - CANADA', '', '', datetime('now')),
('312 - SHRC', '', '', datetime('now')),
('313 - ZDY', '', '', datetime('now')),
('314 - JZM', '', '', datetime('now')),
('315 - SHXY', '', '', datetime('now')),
('316 - SHEKD', '', '', datetime('now')),
('317 - LJJ', '', '', datetime('now')),
('318 - MTMX', '', '', datetime('now')),
('319 - FAS', '', '', datetime('now')),

-- 320-339 段
('320 - 欧诺', '', '', datetime('now')),
('321 - 环赢惠海', '', '', datetime('now')),
('322 - 上海妮尔', '', '', datetime('now')),
('323 - 得玺科技', '', '', datetime('now')),
('324 - BOSS专用', '', '', datetime('now')),
('325 - 潍坊磐隆', '', '', datetime('now')),
('326 - SHNT', '', '', datetime('now')),
('327 - ROBIN', '', '', datetime('now')),
('328 - 秉垚', '', '', datetime('now')),
('329 - 上海屹风', '', '', datetime('now')),
('330 - 士帆', '', '', datetime('now')),
('331 - 上海策融', '', '', datetime('now')),
('332 - 贝斯', '', '', datetime('now')),
('333 - 弘莱', '', '', datetime('now')),
('334 - 优坤宇', '', '', datetime('now')),
('335 - 山西旭日', '', '', datetime('now')),
('336 - 德邦', '', '', datetime('now')),
('337 - 选联', '', '', datetime('now')),
('338 - 阳光跨境', '', '', datetime('now')),
('339 - 松枫', '', '', datetime('now')),

-- 340-363 段
('340 - 上溪-曜信', '', '', datetime('now')),
('341 - 山西诺泽', '', '', datetime('now')),
('342 - 途益-曜信', '', '', datetime('now')),
('343 - 绩溪供应链', '', '', datetime('now')),
('344 - SZLC', '', '', datetime('now')),
('345 - 灿柠', '', '', datetime('now')),
('346 - 李树宏', '', '', datetime('now')),
('347 - 上海澳印科', '', '', datetime('now')),
('348 - SHWY', '', '', datetime('now')),
('349 - 焱林', '', '', datetime('now')),
('350 - SHMX', '', '', datetime('now')),
('351 - JP_TEST', '', '', datetime('now')),
('352 - 青岛雅丰源', '', '', datetime('now')),
('353 - 诺亚', '', '', datetime('now')),
('354 - 苏州同舟', '', '', datetime('now')),
('355 - 苏州韧牛', '', '', datetime('now')),
('356 - 慈信', '', '', datetime('now')),
('357 - 莱工金', '', '', datetime('now')),
('358 - 泉州固德', '', '', datetime('now')),
('359 - 掌骏', '', '', datetime('now')),
('360 - 泉州时颖', '', '', datetime('now')),

-- 364-399 段
('364 - 上海上溪', '', '', datetime('now')),
('365 - 私人物品', '', '', datetime('now')),
('366 - RY代操作', '', '', datetime('now')),
('367 - 魔易客', '', '', datetime('now')),
('368 - 泉州中腾', '', '', datetime('now')),
('369 - 阎一郎', '', '', datetime('now')),
('370 - 龙祥', '', '', datetime('now')),
('371 - 后浪', '', '', datetime('now')),
('372 - 塞亚', '', '', datetime('now')),
('373 - 上海皇承', '', '', datetime('now')),
('374 - 国百万维', '', '', datetime('now')),
('375 - 东方海外仓', '', '', datetime('now')),
('376 - Sky Infinit', '', '', datetime('now')),
('377 - 香港组', '', '', datetime('now')),
('379 - 徐小文', '', '', datetime('now')),
('381 - 青岛暮赫澜', '', '', datetime('now')),
('382 - 开能', '', '', datetime('now')),
('383 - 伊尔升', '', '', datetime('now')),
('384 - ZL', '', '', datetime('now')),
('385 - 英赛轮', '', '', datetime('now')),
('386 - 南通巴士', '', '', datetime('now')),
('388 - TIM周', '', '', datetime('now')),
('390 - 微柳商贸', '', '', datetime('now')),
('391 - 微信winkey', '', '', datetime('now')),
('392 - 珍答', '', '', datetime('now')),
('393 - 乐鱼', '', '', datetime('now')),
('395 - Vicky家具', '', '', datetime('now')),
('396 - 巴士陈总', '', '', datetime('now')),
('397 - 郑铭家具', '', '', datetime('now')),
('398 - 梦马', '', '', datetime('now')),
('399 - 模型空运', '', '', datetime('now')),

-- 400-434 段
('400 - GZ', '', '', datetime('now')),
('401 - David leyva', '', '', datetime('now')),
('402 - 南京新我', '', '', datetime('now')),
('403 - 上海知行合', '', '', datetime('now')),
('405 - 张总', '', '', datetime('now')),
('406 - 镇江瑞航', '', '', datetime('now')),
('407 - CICI', '', '', datetime('now')),
('408 - 开满乐', '', '', datetime('now')),
('409 - 范先琪', '', '', datetime('now')),
('410 - 杭州双鲲', '', '', datetime('now')),
('411 - David泡面', '', '', datetime('now')),
('412 - Dspiae Tool', '', '', datetime('now')),
('413 - 巴士丁总', '', '', datetime('now')),
('414 - 上海承金贸', '', '', datetime('now')),
('415 - 巴士刘总家', '', '', datetime('now')),
('416 - 窗帘用户', '', '', datetime('now')),
('417 - Hyzenhlay', '', '', datetime('now')),
('418 - 竺蓓浩运', '', '', datetime('now')),
('419 - 小五哥客户', '', '', datetime('now')),
('420 - 温州新利宝', '', '', datetime('now')),
('421 - 无锡-Rex容', '', '', datetime('now')),
('422 - 王总（王炳）', '', '', datetime('now')),
('423 - 长乐国际', '', '', datetime('now')),
('424 - 麻辣神山丛', '', '', datetime('now')),
('425 - Jie YAN', '', '', datetime('now')),
('426 - 和横线', '', '', datetime('now')),
('427 - 漳州市永利', '', '', datetime('now')),
('428 - 漏屿商贸', '', '', datetime('now')),
('429 - 成冉', '', '', datetime('now')),
('430 - 王飞大量设', '', '', datetime('now')),
('431 - SCG America', '', '', datetime('now')),
('432 - 禾潞贸易', '', '', datetime('now')),
('433 - 威全锐', '', '', datetime('now')),
('434 - test1-2', '', '', datetime('now')),

-- 其他特殊客户
('321 - 大荣株式会社', '', '', datetime('now')),
('380 - 德立达', '', '', datetime('now')),
('387 - INFINITY', '', '', datetime('now')),
('389 - 巴士优信', '', '', datetime('now')),
('419 - 荣马', '', '', datetime('now')),
('431 - 威适攀', '', '', datetime('now')),
('785 - JET', '', '', datetime('now'));

-- 统计
SELECT '✅ 客户总数：' || COUNT(*) FROM customers;
SELECT '📋 298客户：' || customer_name FROM customers WHERE customer_name LIKE '%298%';